title: GateKeeper Docs
description: Developer and user documentation for the GateKeeper project

remote_theme: just-the-docs/just-the-docs
color_scheme: gatekeeper

url: https://docs.gatekeeper.fun
baseurl: /

# Top links
nav_external_links:
  - title: GateKeeper App
    url: https://app.gatekeeper.fun/
  - title: GitHub Repo
    url: https://github.com/CardanoGateKeeper/GateKeeper

aux_links:
  "Open on GitHub":
    - "//github.com/CardanoGateKeeper/GateKeeper"

footer_content: "© Adam Dean & Latheesan Kanesamoorthy. Built with Jekyll & Just the Docs."
