# /docs/_config.yml
title: GateKeeper Docs
description: Developer and user documentation for the GateKeeper project

remote_theme: just-the-docs/just-the-docs
color_scheme: gatekeeper

# IMPORTANT for Pages under an org/repo:
url: https://cardanogatekeeper.github.io
baseurl: /GateKeeper

# Top links
nav_external_links:
  - title: GateKeeper App
    url: https://summer-reef-yqev1xyzalx8.vapor-farm-b1.com/
  - title: GitHub Repo
    url: https://github.com/CardanoGateKeeper/GateKeeper

aux_links:
  "Open on GitHub":
    - "//github.com/CardanoGateKeeper/GateKeeper"

# Footer (must be plain text—no Ruby interpolation here)
footer_content: "© 2025 GateKeeper. Built with Jekyll & Just the Docs."